notifications:
  email: false
language: c #NOTE: this will set CC=gcc which might cause trouble
before_script:
  - "cd ../ && git clone https://github.com/iot-lab/openlab.git && cd contiki"
  - "sudo apt-get -qq update"
  ## Install these mainline toolchains for all build types
  - "sudo apt-get -qq install lib32z1 || true"
  - "curl -s \
       http://adamdunkels.github.io/contiki-fork/mspgcc-4.7.0-compiled.tar.bz2 \
         | tar xjf - -C /tmp/ && sudo cp -f -r /tmp/msp430/* /usr/local/ && rm -rf /tmp/msp430 && msp430-gcc --version || true"
  - "sudo apt-get -qq install gcc-avr avr-libc || true"
  - "sudo apt-get -qq install libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386 || true"

  ## Install toolchain for mc1233x, cc2538 and mbxxx in care-free way
  - "[ ${BUILD_ARCH:-0} = arm ] && sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded \
        && sudo apt-get update \
        && sudo apt-get -y install gcc-arm-none-eabi || true"

  ## Install SDCC from a purpose-built bundle
  - "[ ${BUILD_ARCH:-0} = 8051 ] && curl -s \
       https://raw.github.com/wiki/g-oikonomou/contiki-sensinode/files/sdcc.tar.gz \
         | tar xzf - -C /tmp/ && sudo cp -f -r /tmp/sdcc/* /usr/local/ && rm -rf /tmp/sdcc && sdcc --version || true"
  - "[ ${BUILD_ARCH:-0} = 8051 ] && sudo apt-get -qq install srecord || true"
  
  ## Clone and build cc65 when testing 6502 ports
  - "[ ${BUILD_ARCH:-0} = 6502 ] && git clone \
       https://github.com/oliverschmidt/cc65 /tmp/cc65 && \
       make -C /tmp/cc65 bin apple2enh atarixl c64 c128 && sudo make -C /tmp/cc65 avail && \
       export CC65_HOME=/tmp/cc65/ && cc65 --version || true"

  ## Compile cooja.jar only when it's going to be needed
  - "[ ${BUILD_CATEGORY:-sim} = sim ] && java -version && ant -q -f tools/cooja/build.xml jar && sudo java -Xshare:dump -version || true"

  ## IMPORTANT: The commands here have to end with `|| true`,
  ## because it would make the test fail if BUILD_TYPE test fails

script:
  ## regression-tests/Makefile handles most of generic logic
  - "make -C examples/kev-runtime"

env:
  - BUILD_TYPE='compile-arm-ports' BUILD_CATEGORY='compile' BUILD_ARCH='arm'
